version: '3.5'

services:
    db:
        image: postgres:14.4-alpine3.16
        container_name: recipe_db
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=recipe
        volumes:
            - db_recipe_volume:/var/lib/postgresql/data

    backend:
        image: recipe
        container_name: backend-app
        depends_on:
            - db
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/recipe
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres

volumes:
    db_recipe_volume:
        external: true
