version: '3.5'

services:
    db:
        image: postgres:14.4-alpine3.16
        container_name: advent_db
        build: .
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=advent
        volumes:
            - db_volume:/var/lib/postgresql/data

volumes:
    db_volume:
        external: true
